name: nervosum-spark-env
channels:
  - defaults
dependencies:
  - pip=20.2.4
  - python=3.8
  - setuptools=50.3.0
  - pip:
#    - conda-pack==0.5.0
#    - pandas==1.1.3
#    - joblib==0.17.0
    - pyspark==3.0.1
#    - scikit-learn==0.23.2
