version: '2'
services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:                                        # mount the following local folders
      - ./jobs:/jobs
      - ./models:/models
  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:                                        # mount the following local folders
      - ./jobs:/jobs
      - ./models:/models
#  spark-job-1:
        ##    build: .
        ##    container_name: spark-job
        ##    depends_on:
      ##      - spark-master
      ##      - spark-worker-1