FROM bde2020/spark-worker:3.0.1-hadoop3.2

RUN echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main" > /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories
RUN apk --no-cache --update-cache add gcc gfortran python3 python3-dev py3-pip py3-setuptools build-base wget freetype-dev libpng-dev openblas-dev
RUN apk add --update --no-cache py3-numpy
# ENV PYTHONPATH=/usr/lib/python3.8/site-packages

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3
RUN type pip3
RUN hash -r
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python3 -c "import sys; print(sys.version)"
RUN cat /etc/*-release
